# This is to be used with https://github.com/davedash/mysql-anonymous.
database:
    truncate:
        - addon_payment_data
        - addon_inapp_log
        - addon_inapp_payment
        - addon_inapp_notice
    tables:
        stats_contributions:
            nullify: [post_data, paykey]
        addon_inapp:
            nullify: [private_key]
